version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  fastapi-app:
    build: .
    container_name: fastapi-worker
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./backend/logs:/app/backend/logs  # ensure logs persist
    restart: always
