version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  fastapi-app:
    build: .
    container_name: fastapi-worker
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/logs:/app/backend/logs
    restart: always

  queue-worker:
    build: .
    container_name: queue-worker
    depends_on:
      - redis
    command: python worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
